### ISSUE TITLE
请问大佬我设置了这个pipeline后为什么里面的大模型都会思考两次啊 = =

### ISSUE THREAD

**Issue by AlickH** [moeakwak/openwebui-api-router-pipeline#1]
如下图所示
<img width="914" alt="Image" src="https://github.com/user-attachments/assets/67dfe947-ab18-4ae1-af45-f52686e05263" />

配置文件如下：
```
providers:
  - key: volcengine
    url: https://ark.cn-beijing.volces.com/api/v3
    api_key: ******
    price_ratio: 0.1
    
  - key: siliconflow
    url: https://api.siliconflow.cn/v1
    api_key: sk-******
    price_ratio: 0.1
    
models:
  - code: deepseek-r1-250120
    provider: volcengine
    human_name: DeepSeek-R1 (Volcengine)
    prompt_price: 2
    completion_price: 8
    no_system_prompt: true
    disable_cost_display_in_completion: true
    
  - code: deepseek-v3-241226
    provider: volcengine
    human_name: DeepSeek-V3 (Volcengine)
    prompt_price: 1
    completion_price: 4
    no_system_prompt: true
    disable_cost_display_in_completion: true

  - code: deepseek-ai/DeepSeek-R1
    provider: siliconflow
    human_name: DeepSeek-R1 (SiliconFlow)
    prompt_price: 2
    completion_price: 8
    no_system_prompt: true
    disable_cost_display_in_completion: true
    
  - code: deepseek-ai/DeepSeek-V3
    provider: siliconflow
    human_name: DeepSeek-V3 (SiliconFlow)
    prompt_price: 1
    completion_price: 4
    no_system_prompt: true
    disable_cost_display_in_completion: true
```
